tracker_node:
  ros__parameters:
    target_frame: "odom"

    tracker:
      max_match_center_xoy: 1.5
      max_match_theta: 1.0
      lost_time_threshold: 1.0
      tracking_threshold: 10

    ekf:
      sigma2_q_xyz: 1.0e-7
      sigma2_q_theta: 1.0
      sigma2_q_r: 1.0e-8

      r_block: 5.0e-6
      r_center: 5.0e-4
      r_block_min: 1.0e-8
      r_center_min: 1.0e-6

    gns:
      min_a: 0.780
      max_a: 1.045
      min_w: 1.884
      max_w: 2.000

      max_iter: 100
      min_step: 1.0e-10
      obs_max_size: 300

      a_start: 0.9125
      w_start: 1.942
      c_start: 0.0
      min_first_solve_time: 4.5

    ekf_gns:
      sigma2_q_a: 0.5
      sigma2_q_w: 0.01
      sigma2_q_c: 100.0

      r_a: 1.0e-8
      r_w: 5.0e-3
      r_c: 1.0e-8
