<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>atri_serial_driver</name>
  <version>1.0.0</version>
  <description>
    Forked from the rm_serial_driver project.
    Serial driver and solve the angles to the target
    Subscribe the moothed target position
    Send the packet to the serial port
  </description>
  <maintainer email="makochishima043@gmail.com">adore</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>

  <depend>atri_interfaces</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>asio_cmake_module</depend>
  <depend>io_context</depend>

  <depend>serial_driver</depend>
  <depend>tf2</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
